//= '../libs/stellar/jquery.stellar.min.js'
//= '../libs/particles/particles.min.js'
//= '../libs/owl/owl.carousel.min.js'
//= '../libs/equal/jquery.equalheights.min.js'
//= '../libs/magnific/jquery.magnific-popup.min.js'
//= '../libs/neko/jquery.appear.js'
//= '../libs/neko/neko.js'
//= 'partials/app.js'
